language: haskell
ghc: 7.8
before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-1.20
  - export PATH=/opt/cabal/1.20/bin:$PATH
  - cabal update
  - cabal install Cabal
  - cd src/
install:
  - cabal install --only-dependencies --enable-tests --allow-newer
after_script:
  - cd .. && ./site build && mv _site/* .
  - git add -A *.html && git commit -m "" && git push
notifications:
  email: false
env:
  global:
    secure: CTK9sm7s/y0FlVQ7N0jSCrxCGpsf5enS0L2igYWJV8pmQerqbfeqoGCkWQP13tJG5yQMvCqee+eactBJriBqYFJ1F12zisRmSLCTZhIFNb7mlcVMeDMQxh4iySjnXVzx8CpnMcRrqFRIHQGtlgTdNKgCGKOJUxHXl5ALeuJOsC4=
