language: haskell
branches:
  only:
    - source
ghc:
  - 7.8
before_install:
  - cd src/
install:
  - cabal install --only-dependencies
  - ghc --make site.hs
script:
  - ./site build
  - cp -R _site/* ../
  - cd ../
after_script:
  - git init
  - git config user.name "travis-worker"
  - git config user.email "travis@gallais.org"
  - git remote add upstream https://${GH_TOKEN}@github.com/gallais/gallais.github.io &>/dev/null
  - git fetch upstream && git reset upstream/master
  - git add *.html *.xml blog/*
  - git commit -m "Uploading snapshot $(date '+%m/%d/%y %H:%M')"
  - git push -q upstream HEAD:master &>/dev/null
notifications:
  email: false
env:
  global:
    secure: "WnJsNJ3xgwuIY6MFfvHvg+fU/m5EB1W6mwAOpLgH3FEzQeKTXVpabQfqkL+kNzHdhN5+muY4/wX+7CpBQMxa4PLuyOVJ7FLxETY03PSEFlS6XwkpN3Ewhq3vOTVVasNSrI5RiLFyuJIbUu0OahJHGQMuCaAMTwARJItc2t7ZsCI="

