dist: trusty

# Using the container-based infrastructure
sudo: false
# Installing ghc 8.0.1, which is not available natively
language: c
matrix:
  include:
#    - env: CABALVER=1.24 GHCVER=8.0.1
      addons:
        apt: 
          packages:
            - ghc
            - libghc-hakyll-dev
            - libghc-text-dev
            - libghc-feed-dev
            - libghc-mtl-dev
            - libghc-parsec3-dev
            - libghc-time-compat-dev 
before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
  - cd src/
install:
#  - cabal update
#  - cabal install --only-dependencies
#:  - cabal configure
  - ghc -v --make site.hs
script:
  - ./site build
  - cp -R _site/* ../
  - cd ../
after_script:
  - git init
  - git config user.name "travis-worker"
  - git config user.email "travis@gallais.org"
  - git remote add upstream https://${GH_TOKEN}@github.com/gallais/gallais.github.io &>/dev/null
  - git fetch upstream && git reset upstream/master
  - git add *.html *.xml blog/* pdf/*
  - git commit -m "Uploading snapshot $(date '+%m/%d/%y %H:%M')"
  - git push -q upstream HEAD:master &>/dev/null
branches:
  only:
    - source
notifications:
  email: false
env:
  global:
    secure: "WnJsNJ3xgwuIY6MFfvHvg+fU/m5EB1W6mwAOpLgH3FEzQeKTXVpabQfqkL+kNzHdhN5+muY4/wX+7CpBQMxa4PLuyOVJ7FLxETY03PSEFlS6XwkpN3Ewhq3vOTVVasNSrI5RiLFyuJIbUu0OahJHGQMuCaAMTwARJItc2t7ZsCI="

