language: haskell
branches:
  only:
    - source
ghc:
  - 7.6
before_install:
  - cd src/
install:
  - cabal install --only-dependencies
  - ghc --make site.hs
script:
  - ./site build
after_script:
  - git fetch && git checkout origin/master
  - mv _site/* ../ && rmdir _site && cd ..
  - git config user.name "travis-worker"
  - git config user.email "travis@gallais.org"
  - git add *.html *.xml blog/*
  - git commit -m "Uploading snapshot $(date '+%m/%d/%y %H:%M')"
  - git push --force https://${GH_TOKEN}@github.com/gallais/gallais.github.io.git origin/master &>/dev/null
notifications:
  email: false
env:
  global:
    secure: "WnJsNJ3xgwuIY6MFfvHvg+fU/m5EB1W6mwAOpLgH3FEzQeKTXVpabQfqkL+kNzHdhN5+muY4/wX+7CpBQMxa4PLuyOVJ7FLxETY03PSEFlS6XwkpN3Ewhq3vOTVVasNSrI5RiLFyuJIbUu0OahJHGQMuCaAMTwARJItc2t7ZsCI="

