language: haskell
ghc:
  - 7.6
before_install:
  - cd src/
after_script:
  - ./site build && mv _site/* . && rmdir _site && cd ..
after_success:
  - git config user.name "travis-worker"
  - git config user.email "travis@gallais.org"
  - git add -A *.html && git commit -m "Upload!" && git push https://$GH_TOKEN@github.com/gallais/gallais.github.io
notifications:
  email: false
env:
  global:
    secure: CTK9sm7s/y0FlVQ7N0jSCrxCGpsf5enS0L2igYWJV8pmQerqbfeqoGCkWQP13tJG5yQMvCqee+eactBJriBqYFJ1F12zisRmSLCTZhIFNb7mlcVMeDMQxh4iySjnXVzx8CpnMcRrqFRIHQGtlgTdNKgCGKOJUxHXl5ALeuJOsC4=
