language: haskell
branches:
  only:
    - source
ghc:
  - 7.6
before_install:
  - cd src/
install:
  - cabal install --only-dependencies
  - ghc --make site.hs
script:
  - ./site build
after_script:
  - git fetch && git checkout origin/master
  - mv _site/* ../ && rmdir _site && cd ..
  - git config user.name "travis-worker"
  - git config user.email "travis@gallais.org"
  - git add *.html *.xml blog/*
  - git commit -m "Uploading snapshot $(date '+%m/%d/%y %H:%M')"
  - git push --force https://${GH_TOKEN}@github.com/gallais/gallais.github.io.git origin/master &>/dev/null
notifications:
  email: false
env:
  global:
    secure: "M+QcCJuavA0DKz5QL4bEYT1B4npHndUio3Gu+1MqjJSE8t4MOxKmHNpEFjjT+yr5YmB2XURH3LR43eDnlMZNomT9NlZiSETZwFB9L2YfehKTDcRuBQ8XcnVqZgsuUXCl0qKmkwHTXcmlGOyZlg4x

