language: haskell
ghc:
  - 7.6
before_install:
  - git checkout master
  - cd src/
install:
  - cabal install --only-dependencies
script:
  - ghc --make site.hs
after_script:
  - ./site build && mv _site/* ../ && rmdir _site && cd ..
  - git status
  - git config user.name "travis-worker"
  - git config user.email "travis@gallais.org"
  - git add *.html blog/*
  - git commit -m "Uploading snapshot $(date '+%m/%d/%y %H:%M')"
  - git push --force https://${GH_TOKEN}@github.com/gallais/gallais.github.io.git master
notifications:
  email: false
env:
  global:
    secure: CTK9sm7s/y0FlVQ7N0jSCrxCGpsf5enS0L2igYWJV8pmQerqbfeqoGCkWQP13tJG5yQMvCqee+eactBJriBqYFJ1F12zisRmSLCTZhIFNb7mlcVMeDMQxh4iySjnXVzx8CpnMcRrqFRIHQGtlgTdNKgCGKOJUxHXl5ALeuJOsC4=
