language: haskell
branches:
  only:
    - source
ghc:
  - 7.6
before_install:
  - cd src/
install:
  - cabal install --only-dependencies
  - ghc --make site.hs
script:
  - ./site build
after_script:
  - mv _site $HOME/
  - cd $HOME
  - git clone --quiet --branch=master https://${GH_TOKEN}@github.com/gallais/gallais.github.io.git terrible-hack &>/dev/null
  - cp -R _site/* terrible-hack/
  - cd terrible-hack/
  - git config user.name "travis-worker"
  - git config user.email "travis@gallais.org"
  - git add *.html *.xml blog/*
  - git commit -m "Uploading snapshot $(date '+%m/%d/%y %H:%M')"
  - git push https://${GH_TOKEN}@github.com/gallais/gallais.github.io.git master &>/dev/null
notifications:
  email: false
env:
  global:
    secure: "WnJsNJ3xgwuIY6MFfvHvg+fU/m5EB1W6mwAOpLgH3FEzQeKTXVpabQfqkL+kNzHdhN5+muY4/wX+7CpBQMxa4PLuyOVJ7FLxETY03PSEFlS6XwkpN3Ewhq3vOTVVasNSrI5RiLFyuJIbUu0OahJHGQMuCaAMTwARJItc2t7ZsCI="

