dist: trusty

# Using the container-based infrastructure
sudo: false
# Installing ghc 8.0.1, which is not available natively
language: haskell

cache:
  directories:
    - $HOME/.cabsnap


before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
  - cd src/

install:
  - sed -i 's/^jobs:/-- jobs:/' $HOME/.cabal/config
  # checking whether .ghc is still valid
  - cabal install --only-dependencies --dry -v > $HOME/installplan.txt
  - sed -i -e '1,/^Resolving /d' $HOME/installplan.txt; cat $HOME/installplan.txt
  - touch $HOME/.cabsnap/intallplan.txt
  - mkdir -p $HOME/.cabsnap/ghc $HOME/.cabsnap/lib $HOME/.cabsnap/share $HOME/.cabsnap/bin
  - if diff -u $HOME/.cabsnap/installplan.txt $HOME/installplan.txt;
    then
      echo "cabal build-cache HIT";
      rm -rfv .ghc;
      cp -a $HOME/.cabsnap/ghc $HOME/.ghc;
      cp -a $HOME/.cabsnap/lib $HOME/.cabsnap/share $HOME/.cabsnap/bin $HOME/.cabal/;
    else
      echo "cabal build-cache MISS";
      rm -rf $HOME/.cabsnap;
      mkdir -p $HOME/.ghc $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin;
    fi
  - cabal install --only-dependencies
  # snapshot package-db on cache miss
  - echo "snapshotting package-db to build-cache";
    mkdir $HOME/.cabsnap;
    cp -a $HOME/.ghc $HOME/.cabsnap/ghc;
    cp -a $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin $HOME/installplan.txt $HOME/.cabsnap/;
  # Actually building the web site
  - ghc -v --make site.hs
script:
  - ./site build
  - cp -R _site/* ../
  - cd ../
after_success:
  - git init
  - git config user.name "travis-worker"
  - git config user.email "travis@gallais.org"
  - git remote add upstream https://${GH_TOKEN}@github.com/gallais/gallais.github.io &>/dev/null
  - git fetch upstream && git reset upstream/master
  - git add *.html *.xml blog/* pdf/*
  - git commit -m "Uploading snapshot $(date '+%m/%d/%y %H:%M')"
  - git push -q upstream HEAD:master &>/dev/null
branches:
  only:
    - source
notifications:
  email: false
env:
  global:
    secure: "WnJsNJ3xgwuIY6MFfvHvg+fU/m5EB1W6mwAOpLgH3FEzQeKTXVpabQfqkL+kNzHdhN5+muY4/wX+7CpBQMxa4PLuyOVJ7FLxETY03PSEFlS6XwkpN3Ewhq3vOTVVasNSrI5RiLFyuJIbUu0OahJHGQMuCaAMTwARJItc2t7ZsCI="

