name: Ubuntu build
on:
  push:
    branches:
      - source
      - build

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.2.0.0"]
        ghc: ["8.6.5"]
    steps:

########################################################################
## INSTALLATION STEP
########################################################################

      - name: Install dependencies
        uses: haskell/actions/setup@v1
        with:
          ghc-version: '${{ matrix.ghc }}'
          cabal-version: '${{ matrix.cabal }}'

      - name: Cache ~/.cabal/store and dist-newstyle
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/store
            ~/src/dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ matrix.cabal }}

########################################################################
## BUILD STEP
########################################################################

      # By default github actions do not pull the repo
      - name: Checkout site
        uses: actions/checkout@v2

      - name: Build site
        run: |
          cd src/
          cabal build
          cabal exec www-gallais build
          cp -R ../css ../pdf ../img ../splv23 _site/

########################################################################
## DEPLOY STEP
########################################################################

      - name: Deploy HTML
        uses: JamesIves/github-pages-deploy-action@4.1.3

        with:
          branch: gh-pages
          folder: src/_site
          git-config-name: Github Actions
